# Generated by Django 2.2.6 on 2019-11-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='blog_slug',
            new_name='slug',
        ),
    ]
